export const CONFIDENT_TRACE_VERBOSE = "CONFIDENT_TRACE_VERBOSE";
export const CONFIDENT_TRACE_SAMPLE_RATE = "CONFIDENT_TRACE_SAMPLE_RATE";
export const CONFIDENT_TRACE_ENVIRONMENT = "CONFIDENT_TRACE_ENVIRONMENT";
export const CONFIDENT_TRACING_ENABLED = "CONFIDENT_TRACING_ENABLED";
